server:
  port: 8082
spring:
  application:
    name: ambassador-service
  cloud:
    discovery:
      enabled: true
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  rest:
    client:
      loadbalancer:
        enabled: true